### ISSUE TITLE
Rakefile modification under Ruby version >= 1.9

### ISSUE THREAD

**Issue by hitalex** [plusjade/jekyll-bootstrap#104]
One whose Ruby version >= 1.9 don't have to "require "rubygems"" in their Rakefile.
See http://docs.rubygems.org/read/chapter/3/

**Comment by groundh0g** [comment]
Given age of issue, and lack of information on the impact, I'm closing this issue for now.

The given link is dead. Is this an issue? Does the inclusion cause problems?

Feel free to reopen if you have more info or concerns.
