### ISSUE TITLE
Border line of table disappeared 

### ISSUE THREAD

**Issue by victorwoo** [plusjade/jekyll-bootstrap#196]
I write a post in markdown, which contains a table:

    | 编号   | 发布时间   | 标题             | PDF       |
    | ------ | ---------- | ---------------- | --------- |
    | Vol.01 | 2013年06月 | 文件系统任务     | [下载][1] |
    | Vol.02 | 2013年07月 | 数组和哈希表     | [下载][2] |
    | Vol.03 | 2013年08月 | 日期、时间和文化 | [下载][3] |
    | Vol.04 | 2013年09月 | 对象和类型       | [下载][4] |
    | Vol.05 | 2013年10月 | WMI              | [下载][5] |
    | Vol.06 | 2013年11月 | 正则表达式       | [下载][6] |

It's ok in preview page:
https://github.com/victorwoo/victorwoo.github.io/blob/master/_posts/powershell-tip/2013-11-12-powertips-monthly.md

But in the generated page, the border lines are disappeared:
http://blog.vichamp.com/powershell/tip/2013/11/12/powertips-monthly/

What's the problem?

**Comment by groundh0g** [comment]
Another old issue. Just cleaning house.

Difference is seen because your style sheet on your published site alters the look of the table cells. Specifically, the following style in [your style.css](http://blog.vichamp.com/css/style.css) at line 623:

```
.article-entry td {
  border-bottom: 1px solid #ddd;
  padding: 10px 0;
}
```

Closing issue.
