### ISSUE TITLE
Can you support a  Chinese comment provider?

### ISSUE THREAD

**Issue by GraphicsMe** [plusjade/jekyll-bootstrap#199]
Duoshuo(http://duoshuo.com/) is one of the main comment provider in China. It would be a great convenience to have it!

**Comment by groundh0g** [comment]
Assigned this to myself. Plan to research the most popular social media outlets around the globe, as well as those that have such similar APIs that they're easily shoehorned into the JB provider model.

If anyone has suggestions for other social media or comment / discussion sites, speak up.

I'm starting from this (and of course, Google searches):

http://vincos.it/world-map-of-social-networks/

**Comment by groundh0g** [comment]
Note: Seems related to PR #120. Two providers identified.

**Comment by groundh0g** [comment]
Should be live as of today's merge of #153 and #184.
