### ISSUE TITLE
No .gitmodules file included in project?

### ISSUE THREAD

**Issue by ahmetabdi** [plusjade/jekyll-bootstrap#200]
The submodule `jekyll-bootstrap` was not properly initialized with a `.gitmodules` file.

Nothing specified in quick start guide into creating one

**Comment by groundh0g** [comment]
Can you provide more detail on what you're looking for? I'm a bit of a GIT newcomer, so the concept is foreign to me. My GIT client (SourceTree) hides most of the command-line fun from me.

Examples and use cases would be most helpful.

Given the age of this issue, I'm closing for now. Feel free to reopen if you want to continue the discussion.

> **Note:** Based on a quick review of `.gitmodules`, I assume you're looking to support themes and customizations? Sorry to be such a know-nothing, but any help / clarification / links to how-to's on this topic you care to offer would be most appreciated.

**Comment by ahmetabdi** [comment]
Not too sure why I opened this but I'm assuming I had to add this file to make it work properly.

https://raw.githubusercontent.com/ahmetabdi/ahmetabdi.github.io/53cbdbd8f42a0d9470e790484641330fbd758aae/.gitmodules

Keep it closed :) :+1:
