### ISSUE TITLE
Generating... error: Invalid argument?

### ISSUE THREAD

**Issue by longrm** [plusjade/jekyll-bootstrap#201]
when i tried like this:

$ git clone https://github.com/plusjade/jekyll-bootstrap.git
$ cd jekyll-bootstrap
$ jekyll serve

then i got an error:

Configuration file: D:/Users/longrm/Documents/My Apps/GitHub Jekyll/_config.yml
            Source: D:/Users/longrm/Documents/My Apps/GitHub Jekyll
       Destination: D:/Users/longrm/Documents/My Apps/GitHub Jekyll/_site
      Generating... error: Invalid argument - D:/Users/longrm/Documents/My Apps/
GitHub Jekyll/_site/D:. Use --trace to view backtrace

why ?

**Comment by groundh0g** [comment]
Based on @Travis-Hironak's comment, closing as resolved. Feel free to reopen if needed.
