### ISSUE TITLE
Not able to paginate index.html?

### ISSUE THREAD

**Issue by mdosch** [plusjade/jekyll-bootstrap#202]
Hi,
I'm trying for 3 days now to get pagination working but there are still all posts shown at index.html instead of just the amount of posts configured.

I'm using the hooligan theme and configured pagination as explained here: http://jekyllrb.com/docs/pagination/

You can have a look at my test-page: http://test.mdosch.de/

Is there any hint to configure this?

Best regards,
Martin

**Comment by groundh0g** [comment]
Adding to list of potential FAQs. May end up being a tweak, as suggested by @flannelJesus.
