### ISSUE TITLE
can't install jekyll-bootstrap

### ISSUE THREAD

**Issue by zendzo** [plusjade/jekyll-bootstrap#203]
i use windows 7, already install ruby and rubygems ..
when i run gem install jekyll
i got error message

**Comment by groundh0g** [comment]
Housecleaning. Closing old issue. Looks like this was resolved. 

@zendzo's site is live [here](http://zendzo.github.io), and looks pretty darned good. =)

**Comment by zendzo** [comment]
Thank you closed

**Comment by zendzo** [comment]
Hai plusjade/jekyll-boot,

Saya ingin menambahkan Anda ke jaringan profesional saya di LinkedIn.

- M.Zaenal

Harap konfirmasi bahwa Anda mengenal M.Zaenal: https://www.linkedin.com/e/v2?e=0-ihmwtpwj-3j&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=rD9N1RzE&invitationId=6077318267830091778








Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=0-ihmwtpwj-3j&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFnmxMCgiwi7wAAAVFb5AovLcmyI4PMxaNBqBnJzIKNH4f5sYwlukDpet0dsmpT4r7Zm04yCoqa3M8MS53KO98Txzc0r17xNvp3fzRt-kSDpSk0UNy6uyFCWiVcg7oYsaWMV_QwP6C33Y-WPcu30HTaBlIPp8ijefWENHAWBQh7MIT7wKb87OOHkZo96FnjBUjW&eid=0-ihmwtpwj-3j


Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ihmwtpwj-3j&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Comment by zendzo** [comment]
M.Zaenal Mustofa would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-eob8mp-ihvg5puh-pm&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=rD9N1RzE&invitationID=6077318267830091778

View M.Zaenal Mustofa&#39;s profile: https://www.linkedin.com/e/v2?e=-eob8mp-ihvg5puh-pm&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=rD9N1RzE&invitationID=6077318267830091778





Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=-eob8mp-ihvg5puh-pm&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-eob8mp-ihvg5puh-pm&loid=AQHfOlV4jMsosAAAAVF7stDSbFumqw6Bu-biK20vRQCzV9aG1rE0F-mPWjqqln58FC990McniYD3E95nGF9B3ev6sewhKQtMLwvfsNkt3KHwKMgJtGEqdTiL4WiTaE6UBY3pJiTpzI5AgyC_jN6GxypZYb8upV8_oYKxK7sakhXb-daDwcyYl2v7GuSyI6m4b6_p

Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-eob8mp-ihvg5puh-pm&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn dan logo LinkedIn adalah merek dagang terdaftar yang dimiliki oleh LinkedIn.

**Comment by zendzo** [comment]
M.Zaenal Mustofa would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-eob8mp-ii6etf12-hn&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=rD9N1RzE&invitationID=6077318267830091778

View M.Zaenal Mustofa&#39;s profile: https://www.linkedin.com/e/v2?e=-eob8mp-ii6etf12-hn&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=rD9N1RzE&invitationID=6077318267830091778





Anda mendapatkan undangan untuk terhubung. LinkedIn akan menggunakan alamat email untuk memberi saran ke anggota lainnya di fitur seperti Orang yang Mungkin Anda Kenal. Berhenti berlangganan di sini: https://www.linkedin.com/e/v2?e=-eob8mp-ii6etf12-hn&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-eob8mp-ii6etf12-hn&loid=AQGtPsi7JCAsuAAAAVGivFEmM1w50DWhcRKeXlrDsPhuhtS9Gj5Tevu-PFcQeVKYD5o1IPVwrTVm69subug3cH_GaRvy9Uv1ubX7eoCoS9heIxWzKI0iEe_0TAqWr9Ouaj-ZWAR-iyk4nQgNOt87S8iZnB1Z7kysYmGvH6J_q-HLteoVQseUeSQ9iO5lqd8b8IvX

Email ini dikirimkan kepada reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-eob8mp-ii6etf12-hn&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
