### ISSUE TITLE
Navigation group as task in Rakefile

### ISSUE THREAD

**Issue by iwx1** [plusjade/jekyll-bootstrap#210]
Is it possible to create a rake task to create navigation item like Pages, Tags, Archive, etc
Mean to say something like rake group name="Resources" title="Resources And Links" 

This should create a file as Resources.md and a folder resources in the root and also a first.md 
Then it should be displayed in the navigation bar, when clicked shows list of links to md or html files available in the resources folder.

I am not experience so asking in this way.
Thanks for feedback and direction! :)

**Comment by groundh0g** [comment]
I know it's not an answer, but this issue is old. Adding to list of possible FAQs and closing child issue.
