### ISSUE TITLE
How to serve static assets?

### ISSUE THREAD

**Issue by misaka-10032** [plusjade/jekyll-bootstrap#229]
I want to attach a picture in my post, how to? How can I reference that asset (of course I cannot reference it with absolute path, because I need to deploy it somewhere else).

**Comment by groundh0g** [comment]
I know this is an old question, but ...

```
<img src="{{ BASE_PATH }}/assets/img/my_cool_image.png" />
```

**Comment by misaka-10032** [comment]
Still useful, many thank! Actually it seems that all the custom assets should be placed under {{ BASE_PATH }}/assets, otherwise it cannot be found.
