### ISSUE TITLE
ERROR -- : Actor crashed! Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external

### ISSUE THREAD

**Issue by jaywcjlove** [plusjade/jekyll-bootstrap#230]
````
ERROR -- : Actor crashed!
Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external
````

**Comment by groundh0g** [comment]
Did you ever resolve this issue? If not, can you give a little more detail? (e.g. foreign languages(?), dependency versions, error seen locally or on gh-pages, ...)

**Comment by jaywcjlove** [comment]
Has been resolved. Thank you！

**Comment by groundh0g** [comment]
Thanks for the update, @jaywcjlove. My google-fu is strong, but suggested fixes were all over the map on this. Not enough detail to narrow down. =)

**Comment by carizzapanopio** [comment]
how did you solve this issue??? PLEASE HELP!!!!!!!  :(
