### ISSUE TITLE
Search bar useful?

### ISSUE THREAD

**Issue by erikmartinessanches** [plusjade/jekyll-bootstrap#235]
Is the search bar meant to be used, for site-wide searches, considering the static nature of Jekyll? The search bar in the default Jekyll Bootstrap setup doesn't work for me.

**Comment by groundh0g** [comment]
It's a placeholder. You can implement your own, or (more likely) create a custom search with something like https://www.google.com/cse/ or ...

```
  <form class="navbar-form navbar-right" role="search" method="get" action="http://www.bing.com/search">
	<div class="form-group">
	  <input type="text" class="form-control" placeholder="Search" name="q" />
	  <input type="hidden" name="q1" value="site:wikipedia.org" />
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
  </form>
```

... you can replace the existing search box in `_includes/themes/{themename}/default.html` something like that. (Obviously, you'll need to replace "wikipedia.org" with your site.)

**Comment by plusjade** [comment]
I use https://swiftype.com/ , a javascript-based third-party search tool great for jekyll sites.

**Comment by groundh0g** [comment]
Assigned this to myself. Plan to implement a provider model similar to comments and analytics where you can pick from several search providers, or create a custom one using those as examples.

Thinking about adding the following to start.

* SimpleSearch: https://github.com/christian-fei/Simple-Jekyll-Search 
* SwiftType: https://github.com/plusjade/jekyll-bootstrap/issues/235#issuecomment-76303121 
* Google: http://traceyspencer.blogspot.com/2012/02/adding-google-custom-search-form.html 
* Bing: https://github.com/plusjade/jekyll-bootstrap/issues/235#issuecomment-76175707 
* Yahoo: https://search.yahoo.com/search?p=coffee+site%3Afauxcabulary.org
* DuckDuckGo: https://duckduckgo.com/?q=coffee+site%3Afauxcabulary.org
* Dogpile: http://www.dogpile.com/search/web?q=coffee+site%3Afauxcabulary.org
* IxQuick: https://ixquick.com/do/search?q=coffee+site%3Afauxcabulary.org 

Feel free to comment, interject, or object.

**Comment by groundh0g** [comment]
Plugin might be too elaborate for this. I use a simple JS solution (like @plusjade). It's clean, looks nice, and just works. If I do go the plugin route, this will get bumped to next release.

**Comment by groundh0g** [comment]
Moving to FAQ / Tutorial. Great ideas, but not practical for vanilla installation of JB.
