### ISSUE TITLE
Code block Markdown not rendering correctly in post

### ISSUE THREAD

**Issue by ryankbales** [plusjade/jekyll-bootstrap#238]
This is what I input in my post...

``` javascript
    $.ajax({
        async: false,
        url: '/play/update_bank',
        dataType: 'json',
        contentType: 'application/json',
        type: 'POST',
        data: JSON.stringify({new_value: new_value}),
        success: function(json) {
        alert("You are in the success function");
        }
    });
```

This is what it looks like...

![screen shot 2014-12-19 at 10 42 20 pm](https://cloud.githubusercontent.com/assets/2401893/5514000/624b98da-87d0-11e4-94c5-cc892dcb6665.png)

Seems to kind of work, but as you can see, it renders it out inline and prints the 'javascript' identifier.  What am I doing wrong?

**Comment by ryankbales** [comment]
@plusjade Are you guys maintaining this repo anymore?  Just curious on how I could fix this markdown issue that I reported a couple weeks back.  Let me know if I can help.

**Comment by zhangmhao** [comment]
@ryankbales , I ran into the same problem too, and I add markdown config in  the `_config.yml` file, problem solved!
```
markdown: redcarpet
```

**Comment by ryankbales** [comment]
@zhangmhao This worked.  Thanks!

**Comment by henryaj** [comment]
@zhangmhao - perfect. Thank you!
