### ISSUE TITLE
Support for bitbucket?

### ISSUE THREAD

**Issue by Jiraiyah** [plusjade/jekyll-bootstrap#239]
Hi i don't have a repository on git but I have one in bitbucket, can you please add support for bitbucket repository accounts too? thanks

**Comment by cdslashetc** [comment]
I am new to this myself, but I have found out that Bitbucket is not based on Jekyll but you still can install Jekyll on your own computer and compile the site there then you can push the results to Bitbucket.  Here are a couple articles that may be helpful:

+ [Building a blog using jekyll on Bitbucket](http://m00nlight.bitbucket.org/miscellaneous/2014/01/03/building-a-blog-using-jekyll-on-bitbucket.html)
+ [Jekyll on Bitbucket](http://isti.bitbucket.org/2012/04/01/jekyll-on-bitbucket.html)

I also suggest installing RVM on your computer in case you need to make changes to Ruby without breaking operating system software that also depends on Ruby.

+ [RVM: Ruby Version Manager - Installing RVM](https://rvm.io/rvm/install)

**Comment by groundh0g** [comment]
@Jiraiyah did you find @cdslashetc's answer satisfactory? Looks like a great overview!

A cursory review of Bitbucket's static page hosting leads me to believe building local and committing to Bitbucket may be your only option, as stated by @cdslashetc.

**Comment by groundh0g** [comment]
Closing this issue. Adding to list for possible FAQs.
