### ISSUE TITLE
error on trying any plugin !! please help

### ISSUE THREAD

**Issue by Jiraiyah** [plusjade/jekyll-bootstrap#240]
ok, I tried this plugin first : 
https://github.com/pravj/Harry/blob/master/harry.rb
and i got the error i posted in this issue : 
https://github.com/pravj/Harry/issues/7

but then i noticed i get this error for every plugin i try, what is going on? using hooligan template by the way

**Comment by groundh0g** [comment]
Looks like you resolved the issue in the other thread? Closing. This one.
