### ISSUE TITLE
Rake Task Help

### ISSUE THREAD

**Issue by ryankbales** [plusjade/jekyll-bootstrap#242]
This is more than likely not an issue with jekyll-bootstrap rather a local configuration setting that isn't working right.

When attempting to use the rake task to create a post I get: 'Could not locate gemfile.'

I have both Bundler and Rake installed and still getting the same thing.  Any help or system checks I can look at would be much appreciated.  Thanks!

**Comment by groundh0g** [comment]
What OS? If Windows, and you're using pygments, you'll need the python stuff + gem.

In any case. Have you tried these?

```
gem update --system
```

and

```
gem update jekyll
```

**Comment by groundh0g** [comment]
While this is one of the newer issues in the repo, it's of a type that I expect @ryankbales solved on their own using google or stackoverflow. If you still need help, feel free to reopen. Please include as much detail as you deem necessary to resolve. Thanks!
