### ISSUE TITLE
404 with Github Pages

### ISSUE THREAD

**Issue by NVentimiglia** [plusjade/jekyll-bootstrap#267]
Hey I am trying to setup a github pages blog. I can get the project to run locally but whenever I look at the blog on github pages I get a 404 error.

http://nventimiglia.github.io/jekyll-bootstrap

> The site configured at this address does not contain the requested file.

>If this is your site, make sure that the filename case matches the URL.
>For root URLs (like http://example.com/) you must provide an index.html file.

>Read the full documentation for more information about using GitHub Pages.

Please Advise

**Comment by groundh0g** [comment]
http://jekyllbootstrap.com/usage/jekyll-quick-start.html

Paste `nventimiglia` into the textbox on that page to personalize the instructions.

Basically, your repo has to have a specific name. In your case, "nventimiglia.github.com". Take a peek at the instructions and let me know if they work for you.

**Comment by groundh0g** [comment]
The ".com" may be ".io". I just checked my repo and it's `groundh0g.github.io` ...

https://github.com/groundh0g/groundh0g.github.io

**Comment by NVentimiglia** [comment]
Ok, I have some progress. Girhub pages requires content to be in a gh-pages branch.
https://help.github.com/articles/creating-project-pages-manually/

Perhaps this step should be added to the docs.

I may be back as my install is still broken (no css).

**Comment by groundh0g** [comment]
Sorry. Thought you were doing a personal page. =)

Yep. Project pages have to be in a gh-pages branch.
