### ISSUE TITLE
CSS 404

### ISSUE THREAD

**Issue by NVentimiglia** [plusjade/jekyll-bootstrap#268]
An unmodified install produces invalid css links.

````
 <!-- Bootstrap styles -->
    <link href="/assets/themes/bootstrap-3/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Optional theme -->
    <link href="/assets/themes/bootstrap-3/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <!-- Sticky Footer -->
    <link href="/assets/themes/bootstrap-3/bootstrap/css/bs-sticky-footer.css" rel="stylesheet">
    
    <!-- Custom styles -->
    <link href="/assets/themes/bootstrap-3/css/style.css?body=1" rel="stylesheet" type="text/css" media="all">
````

When I removed the leading **'/'** the linker worked. I am investigating how to resolve this.

See : http://nventimiglia.github.io/NVentimiglia/

Related (I think) my url paths are also incorrect. For instance,

Archives links to :
http://nventimiglia.github.io/archive.html

Instead of 
http://nventimiglia.github.io/Nventimiglia/archive.html

I have tried many settings inside my config file, nothing is working.

**Comment by groundh0g** [comment]
Check your `_config.yaml`. Depending on where those links live, you'll need to set the BASE_PATH or ASSET_PATH since your URL points to a folder on the site. Try setting your JB.BASE_PATH to `//nventimiglia.github.io/nventimiglia`. e.g.:

```
JB :
  version : 0.3.0

  # All links will be namespaced by BASE_PATH if defined.
  # Links in your website should always be prefixed with {{BASE_PATH}}
  # however this value will be dynamically changed depending on your deployment situation.
  #
  # CNAME (http://yourcustomdomain.com)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Pages (http://username.github.io)
  #   DO NOT SET BASE_PATH 
  #   (urls will be prefixed with "/" and work relatively)
  #
  # GitHub Project Pages (http://username.github.io/project-name)
  #
  #   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
  #  REQUIRED! Set BASE_PATH to: http://username.github.io/project-name
  BASE_PATH : //nventimiglia.github.io/nventimiglia

  # By default, the asset_path is automatically defined relative to BASE_PATH plus the enabled theme.
  # ex: [BASE_PATH]/assets/themes/[THEME-NAME]
  #
  ASSET_PATH : false
```

**Comment by NVentimiglia** [comment]
Ive been playing with the Base_Path and Asset path for the last 10 min or so. I have tried many combinations including the one you suggested.

**Comment by groundh0g** [comment]
Looking at your latest `_config.yaml`, I'd guess:

* set `production_url: NVentimiglia`
* set `BASE_PATH : http://nventimiglia.github.io/NVentimiglia/` (it already is)
* set `ASSET_PATH : false` (it already is)

**Comment by plusjade** [comment]
Could be the new changes with regard to `is_production` variable not giving the proper value? That is, the base path should be honored in production (github pages) and set to the sub-folder. However, it should NOT be honored in development where the path should be /. @NVentimiglia does it work fine locally?

**Comment by plusjade** [comment]
You might try rendering the value is `is_production` within the HTML itself so you can see what it is set to when you host it on github pages. @groundh0g might be of more help since I don't know the exact syntax for echoing the `is_production` variable at the moment.

**Comment by groundh0g** [comment]
Should look like this:

```
{% include JB/is_production %}
<p>is_production = '{{ is_production }}'</p>
<p>jb_prod_env = '{{ jb_prod_env }}'</p>
```

I would expect `false`/`development ` for development (localhost) and `true`/`github ` for GitHub Pages.

**Comment by NVentimiglia** [comment]
> set production_url: NVentimiglia

Done, no change =(

Where should I place the {% include JB/is_production %} ? I placed it in index.md for now (no change)

**Comment by NVentimiglia** [comment]
http://localhost:4000/ works fine.

**Comment by plusjade** [comment]
put  this in the index.md file so that it outputs into HTML:

```html
{% include JB/is_production %}
<p>is_production = '{{ is_production }}'</p>
<p>jb_prod_env = '{{ jb_prod_env }}'</p>
<p>BASE_PATH = '{{ BASE_PATH }}'</p>
<p>ASSET_PATH = '{{ ASSET_PATH }}'</p>


{% include JB/setup %}
<p>is_production = '{{ is_production }}'</p>
<p>jb_prod_env = '{{ jb_prod_env }}'</p>
<p>BASE_PATH = '{{ BASE_PATH }}'</p>
<p>ASSET_PATH = '{{ ASSET_PATH }}'</p>

```

Then commit. This will not fix the problem, it will help diagnose it.

**Comment by groundh0g** [comment]
To be clear `{% include JB/setup %}` doesn't tell jekyll-bootstrap that it's in production mode. It's a script that tries to detect production mode.

https://github.com/NVentimiglia/NVentimiglia/commit/f61d723d8f0c3a4e11ba88de4459c71942deaf84#diff-d680e8a854a7cbad6d490c445cba2eba

Try pasting the entire block that @plusjade suggested. Then we'll take a look at the output.

**Comment by groundh0g** [comment]
I just committed the change to my pages site ... 

http://groundh0g.github.io/test_prod.html

Seems fine?

**Comment by groundh0g** [comment]
# Script:

```
{% include JB/is_production %}
<p>is_production = '{{ is_production }}'</p>
<p>jb_prod_env = '{{ jb_prod_env }}'</p>
<p>BASE_PATH = '{{ BASE_PATH }}'</p>
<p>ASSET_PATH = '{{ ASSET_PATH }}'</p>

{% include JB/setup %}
<p>is_production = '{{ is_production }}'</p>
<p>jb_prod_env = '{{ jb_prod_env }}'</p>
<p>BASE_PATH = '{{ BASE_PATH }}'</p>
<p>ASSET_PATH = '{{ ASSET_PATH }}'</p>
```

# Output:

```
is_production = 'true'
jb_prod_env = 'github'
BASE_PATH = ''
ASSET_PATH = '/assets/themes/'

is_production = 'true'
jb_prod_env = 'github'
BASE_PATH = ''
ASSET_PATH = '/assets/themes/'
```

**Comment by plusjade** [comment]
You should try to set a custom base path and check if it correctly
manipulates the paths in production

**Comment by groundh0g** [comment]
Also fine...

# Output

```
is_production = 'true'
jb_prod_env = 'github'
BASE_PATH = '//groundh0g.github.io/'
ASSET_PATH = '//groundh0g.github.io//assets/themes/'

is_production = 'true'
jb_prod_env = 'github'
BASE_PATH = '//groundh0g.github.io/'
ASSET_PATH = '//groundh0g.github.io//assets/themes/'
```

... worth noting that `production_url` is, and has always been:

```
# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://groundh0g.github.io
```

**Comment by NVentimiglia** [comment]
Is there a way to force a rebuild of the application ? I updated index.md and noticed nothing changed. I changed the content around and still nothing changed. I also cleared my cache and nothing changed.

**Comment by groundh0g** [comment]
Github triggers a build on commit almost immediately. Unless it's cached in your browser (which you cleared), should show up before you can alt-tab to view the change.

**Comment by NVentimiglia** [comment]
Thanks for your help guys, it was 100% my bad.

I was working on master, not gh-pages. Wrong branch. Wow.

**Comment by plusjade** [comment]
To be fair,  that is a common problem.  Jekyll assumes an above average
command of git.   However a large part of jekylls demographic consist of
basic website generation.  The inspiration for jb is to try to bridge that
gap.  It's clear more intuitive tools are still needed =p

**Comment by groundh0g** [comment]
LOL. Been there. Done that. Glad you're up and running!
