### ISSUE TITLE
Default ASSET_PATH fails for latest jekyll version

### ISSUE THREAD

**Issue by brbrr** [plusjade/jekyll-bootstrap#290]
serving default jekyll-bootstrap blog with latest (3.0.0) jekyll will not load assets for blogs i.e. `core-samples/lessons/2011/12/29/jekyll-introduction`
Looks like with new verison Jekyll/Liquid front matter do not inherit theme variable from layouts, thats why `page.theme.name` is empty.

as workaround its possible to define theme for every post, or define ASSET_PATH directly in config.

btw - why not to define theme variable in config file to use in `JB/setup` ? 

UPD: as for jekyll 3.0 layout variables now accessible with `layout.variable`. So updating `JB/setup`'s capture of ASSET_PATH would resolve issue but only for posts. 

I'm not sure why, but it still wont work for any `layout: page`  pages.

Here is my workaroud

```
# JB/setup
{% capture ASSET_PATH %}{{ BASE_PATH }}/assets/themes/{{ site.JB.THEME }}{% endcapture %}

# _config.yml
JB :
  THEME : bootstrap-3
```

**Comment by tops357** [comment]
Had the same problem. The solution for the Bootstrap Theme included the above hack and:

1. Rename /assets/themes/bootstrap-3 to bootstrap
2. Rename /assets/themes/bootstrap/css to css-backup
3. Move /assets/themes/bootstrap/bootstrap folders (css, fonts, js) to /assets/themes/bootstrap

Not very pretty, but it works for my site.

**Comment by wesleywerner** [comment]
@tops357 if you replace your `#2` with:

    mv /assets/themes/bootstrap/css /assets/themes/

then if will also fix the `style.css` file. But I see switching to another theme breaks this hack too.

What works for me is:

1. `rake theme:switch name="bootstrap-3/twitter"`
2. define ASSET_PATH directly in config as pointed out by @brbrr - `ASSET_PATH : /assets/themes/{bootstrap-3/twitter}`

Unfortunate it is a double-barrel step but it works.

**Comment by bdeanindy** [comment]
A quick cheat for this (if you just need to get things working and you want to use a theme, for instance I was using the `hooligan` theme which I really like).

I just opened the `/_config.yml` and changed `ASSET_PATH` to be `/assets/themes/hooligan`.

That seemed to do the trick (for now until I can figure out what the heck is causing the theme.name value to get lost).

I know this is a total hack, but I was looking for a "single location" to make the changes I needed and that seemed to do the trick (so I could leave all the other structure alone).

Hope it helps someone.

**Comment by wizardxbl** [comment]
I have the same problem.
when i run jekyll serve
i can see the index.html for first page, it has right theme
but the other pages has no theme.

the right link is like is:
<link href="/assets/themes/bootstrap-3/bootstrap/css/bootstrap.min.css" rel="stylesheet">
but the wrong link is：
<link href="/assets/themes//bootstrap/css/bootstrap.min.css" rel="stylesheet">

i try the layout.theme.name but not work for me.....

**Comment by seoyoochan** [comment]
this is still not working... i had to manually set `ASSET_PATH` with the theme name

**Comment by lefttree** [comment]
Have the same problem when I run `jekyll serve` on Mac. It's always trying to find assets at `/assets/themes/` directory instead of `/assets/themes/<theme name>`. 

Hack as above to manually change the `ASSET_PATH`, hope for a better solution.

**Comment by yanhaijing** [comment]
i have same question

**Comment by reznoa** [comment]
i have same problem, too.
i think it cause by GitHub Pages's change.
maybe manual set `ASSET_PATH` is only soulution.

**Comment by einverne** [comment]
@qh 's patch is worked. See https://github.com/qh/jekyll-bootstrap/commit/a1d17efdb782a6ce343458d9e8af1d510efb71d9 or https://github.com/plusjade/jekyll-bootstrap/pull/293

**Comment by einverne** [comment]
@qh 's patch is working. See https://github.com/qh/jekyll-bootstrap/commit/a1d17efdb782a6ce343458d9e8af1d510efb71d9 or https://github.com/plusjade/jekyll-bootstrap/pull/293

**Comment by brbrr** [comment]
Closing, as #293 was merged in to develop branch.

**Comment by dsposito** [comment]
Thanks for documenting a fix here. :+1: Setting ASSET_PATH in my config did the trick.

**Comment by 1kohei1** [comment]
Thanks for this issue!
It was trouble some last several months!
