### ISSUE TITLE
Problems with {{ ASSET_PATH }} in Jekyll 3.1.1

### ISSUE THREAD

**Issue by ploeh** [plusjade/jekyll-bootstrap#295]
Please accept my apologies in advance if this issue is inappropriate, or if it's a duplicate.

Since [GitHub Pages updated to run on Jekyll 3.0 February 1, 2016](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0), `{{ ASSET_PATH }}` no longer includes the theme on my site.

As an example, this:

```
<link href="{{ ASSET_PATH }}/bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

generates this:

```
<link href="/assets/themes//bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

(notice the double slashes between `themes` and `bootstrap`) while I would have expected it to generate this:

```
<link href="/assets/themes/ploeh/bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

which Jekyll 2 did.

I'm neither a Jekyll expert nor a Ruby programmer, but AFAICT, `ASSET_PATH` is built in `JB/Setup`. Here, it uses `{{ page.theme.name }}`, but as far as I can tell, this expression evaluates to nothing (or the empty string).

My `_layout` files essentially look like the following, so I can't figure out what I'm doing wrong:

**default.hml**

```
---
theme :
  name : ploeh
---
{% include JB/setup %}
{% include themes/ploeh/default.html %}
```

**page.html**

```---
theme :
  name : ploeh
layout: default
---
{% include JB/setup %}
{% include themes/ploeh/page.html %}
```

**post.html**

```---
theme :
  name : ploeh
layout: default
---
{% include JB/setup %}
{% include themes/ploeh/post.html %}
```

My entire site's source code is [publicly available](https://github.com/ploeh/ploeh.github.com), if that's any help.

What am I doing wrong, and what can I do to correct the problem?

**Comment by ploeh** [comment]
I may have found the problem. In `JB/Setup` the script uses `{{ page.theme.name }}`, but it seems that in Jekyll 3, it has to be `{{ layout.theme.name }}`.

Making this change seems to solve my problem.

Is this expected?

**Comment by parkr** [comment]
@ploeh In Jekyll, yes. See: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata

**Comment by einverne** [comment]
It seems the same issue as https://github.com/plusjade/jekyll-bootstrap/issues/290 .

**Comment by ploeh** [comment]
Perhaps. It fixes issues with posts, but not with other pages.

Right now I'm resorting to the hack setting `ASSET_PATH` in `_config.yml`.

**Comment by groundh0g** [comment]
@ploeh I'm guessing the issue with the other pages might be that they're no longer generated with extensions. So "/archive.html" is now "/archive/", "/tags.html" is now "/tags/", etc ....

I had to make that tweak on my default.html  header navigation links under `_includes/themes/mytheme/`.

I'll make sure there's not already one, then issue a PR later this week.

**Comment by groundh0g** [comment]
Add to the list the following edit in `_config.yml` ...

```
-  archive_path: /archive.html
-  categories_path : /categories.html
-  tags_path : /tags.html
+  archive_path: /archive/
+  categories_path : /categories/
+  tags_path : /tags/
```

**Comment by ploeh** [comment]
No, that doesn't help.

Or rather, it looks fine on my machine, but when hosted by GitHub Pages, all styling is gone.

**Comment by groundh0g** [comment]
Hmmm. Could be the permalink?

```
-permalink: /:categories/:year/:month/:day/:title 
+permalink: /:categories/:year/:month/:day/:title/
```

(Note the trailing `/`.)

Guessing based on: 1) I made that edit in my `_config.yml` earlier, and 2) the [jekyll 3.x upgrade docs](http://jekyllrb.com/docs/upgrading/2-to-3/#permalinks-no-longer-automatically-add-a-trailing-slash) mention it.

If you don't mind, give that a go and let me know.

**Comment by groundh0g** [comment]
Never mind. The symptom for that would be a 404 error. Still probably needs to be tweaked, though.

**Comment by ploeh** [comment]
Thank you, but it's not that either...

**Comment by agautam-hs** [comment]
Ok... so upgrade broke my website too (http://www.ajaygautam.com)
Filed details at https://talk.jekyllrb.com/t/3-x-upgrade-issues/1965 and someone redirected me here.

changing {{ page.theme.name }} to {{ layout.theme.name }} fixes everything except my home page!
Any idea what may be wrong?

Thanks

Ajay

**Comment by agautam-hs** [comment]
just saw ploeh's post above. Updated ASSET_PATH in _config.yml - that fixed the issue, but its a very icky solution/workaround.

If anyone knows of a better solution, please post here.

Thanks

**Comment by lcolladotor** [comment]
Using both https://github.com/plusjade/jekyll-bootstrap/issues/295#issuecomment-178869307 and changing the `ASSET_PATH` fixed my website. Thanks!

**Comment by hbrysiewicz** [comment]
I also have this problem and have updated to Jekyll 3 but am wondering how to update jekyll-bootstrap? I have a blog running on 0.2.13 but would like to update it and can't find anything in the docs.

**Comment by ploeh** [comment]
> I also have this problem and have updated to Jekyll 3 but am wondering how to update jekyll-bootstrap?

I simply* pulled down the changes from the the Jekyll Bootstrap remote and merged them. I don't know how your blog is set up, but mine is configured like this:

```
$ git remote --verbose
jekyll-bootstrap        https://github.com/plusjade/jekyll-bootstrap.git (fetch)
jekyll-bootstrap        https://github.com/plusjade/jekyll-bootstrap.git (push)
origin  https://github.com/ploeh/ploeh.github.com.git (fetch)
origin  https://github.com/ploeh/ploeh.github.com.git (push)
```

*Actually, it wasn't _that_ simple, because I had to deal with a handful of merge conflicts, but I managed...
