### ISSUE TITLE
No way to order post or pages

### ISSUE THREAD

**Issue by plusjade** [plusjade/jekyll-bootstrap#42]
I notice people search for how to order page and post lists in Jekyll Bootstrap. Just so there is a place where this question is answered: 

**There is currently no way to pragmatically order pages or posts.**

The posts are ordered chronologically, while the pages are ordered alphabetically (to my knowledge). 

The only way to create your own order is to manually create an array in the _config.yml or YAML Front Matter pointing to the post/page urls, then iterate over that array.

This is one of the biggest drawbacks to sticking with the Jekyll framework. I'm currently scheming a solution for this =)

**Comment by groundh0g** [comment]
I think something like this should work. I tested it locally and all seems well.

## JB/sort_collection
```
{% comment %}

  Sort the given array or map.
  
  Parameters:
    collection: the array or map to sort [REQUIRED]
    sort_by: the property to sort by [OPTIONAL]

  Returns:
    sort_result: the sorted collection

  Examples:
    <h3>Pages</h3>
    <ol>
      {% include JB/sort_collection collection=site.pages sort_by="title" %}
      {% assign pages_list = sort_result %}
      {% include JB/pages_list %}
    </ol>

    <h3>Array</h3>
    <ol>
      {% assign test_array = "one,two,three,four" | split: "," %}
      {% include JB/sort_collection collection=test_array %}
      {% for test in sort_result %}
        <li>{{test}}</li>
      {% endfor %}
    </ol>

{% endcomment %}

{% assign is_array = true %}
{% assign sort_result = "," | split: "," %}
{% assign collection = include.collection %}
{% if include.sort_by %}
  {% assign sort_by = include.sort_by %}
{% else %}
  {% assign sort_by = "title" %}
{% endif %}

{% if collection and collection.size > 0 %}
  {% for x in collection.first %}
    {% if x[1].size > 0 %}
      {% assign is_array = false %}
    {% endif %}
    {% break %}
  {% endfor %}

  {% if is_array == false %}
    {% assign sort_result = collection | sort: sort_by %}
  {% else %}
    {% assign sort_result = collection | sort %}
  {% endif %}
{% endif %}
```

I plan to create a PR for this tonight. Offering up for peer review.

**Comment by groundh0g** [comment]
Merged. Low risk. Stand-alone helper file.
