### ISSUE TITLE
site.safe isn't the right way to set "production" mode

### ISSUE THREAD

**Issue by tommyblue** [plusjade/jekyll-bootstrap#84]
I think that using **site.safe** as flag for **production mode** isn't the right way to do it. 

This only works on Github because it uses *--safe* when the site is generated. I think that the real purpose of *--safe* used by Github is a matter of security. This can be false outside it, e.g. on my own server, Heroku or wherever I'm deploying my site and if I want to use a custom plugin (disabled by *--safe*).

This generates big confusion when migrating from/to github or when developing a generic theme, I think you should find a better way (custom option?) to define a **production mode**

**Comment by groundh0g** [comment]
According to https://help.github.com/articles/using-jekyll-with-pages/, GitHub Pages injects a "github:" metadata blob in the YAML. I'll run a few tests, but if that's true, looking for a non-empty "site.github" value might be a viable means of detecting production mode for GitHub Pages.

**Comment by groundh0g** [comment]
I just committed a solution at https://github.com/groundh0g/jekyll-bootstrap/commit/8fe0db836f0d946e39a8eabaa4c0b975d1c356b6.

I still need to run some tests before I issue a pull request, but I wanted to open the floor to comments / concerns.

Note that GitHub Pages is given priority. The generic Jekyll environment check may indicate a production build, but the GitHub Pages check immediately follows, overriding the generic.

**Comment by groundh0g** [comment]
Added note (line-item comment), based on @AleksueiR's commit, to look at tweaking how JB/setup works.

https://github.com/groundh0g/jekyll-bootstrap/commit/8fe0db836f0d946e39a8eabaa4c0b975d1c356b6#commitcomment-10424717

**Comment by groundh0g** [comment]
This is officially the last issue in v0.4.0 milestone. If you have comments on this, or any of the other issues in v0.4.0, please feel free to speak up. (Preferably in the issue that concerns you.)

https://github.com/plusjade/jekyll-bootstrap/issues?utf8=%E2%9C%93&q=milestone%3A%22v+0.4.0%22+

**Comment by groundh0g** [comment]
I'll commit this tonight and label master.

Missed due date by one day. D'Oh! =)

**Comment by groundh0g** [comment]
I got distracted by a shiny object - continuous integration with Jenkins in a Docker container. Long story, but promising stuff there.

Good to take the extra time, though. On further reflection, I don't think @AleksueiR's patch will be needed in the new logic. Plugins should work just fine, and sharing should still be disabled unless "production" mode is detected.

**Comment by groundh0g** [comment]
After a false start, this appears to be merged now.
