### ISSUE TITLE
Gist integration

### ISSUE THREAD

**Issue by tullyliu** [plusjade/jekyll-bootstrap#98]
JB can support the gist integration just like gist tag in octpress?

(http://brandontilley.com/2011/01/30/gist-tag-for-jekyll.html)
and
(http://blog.55minutes.com/2012/03/liquid-gist-tag-for-jekyll/)

show the jekyll plugin way.

**Comment by groundh0g** [comment]
Looking for low-hanging fruit to get my feet wet on this repo. Looks like a good candidate.

I'll poke around to see if this is still the preferred solution, then implement as a PR.

**Comment by groundh0g** [comment]
Looks like Jekyll beat us to the punch ...

(http://jekyllrb.com/docs/templates/#gist)[http://jekyllrb.com/docs/templates/#gist]

**Comment by groundh0g** [comment]
Stand-alone addition to utility functions. Low risk. Merged as https://github.com/plusjade/jekyll-bootstrap/pull/243.
